apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../components/repo-url

resources:
  - infra.yaml
  - applications.yaml

replacements:
  - source:
      kind: ConfigMap
      name: repo-config
      fieldPath: data.url
    targets:
      - select:
          kind: ApplicationSet
        fieldPaths:
          - spec.generators.0.git.repoURL
          - spec.generators.0.git.values.repoURL
  - source:
      kind: ConfigMap
      name: repo-config
      fieldPath: data.manifest_revision
    targets:
      - select:
          kind: ApplicationSet
        fieldPaths:
          - spec.generators.0.git.revision
