apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  name: playground
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: playground
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - git:
        repoURL: https://github.com/Hoangvu75/k8s_manifest.git
        revision: "master"
        requeueAfterSeconds: 20
        files:
          - path: "apps/playground/**/config.yaml"
        values:
          cluster: "{{index .path.segments 1}}"
          project: "{{index .path.segments 1}}"
          app_path: "{{.path.path}}"
          name: "{{.path.basename}}"
  template:
    metadata:
      name: '{{ default ( printf "%s-%s" .values.project ( index .path.segments 2 ) ) .appName }}'
      namespace: argocd
    spec:
      destination:
        namespace: '{{ default ( index .path.segments 2 ) .destNamespace }}'
        server: https://kubernetes.default.svc
      project: '{{.values.project}}'
      source:
        repoURL: '{{ default "https://github.com/Hoangvu75/k8s_manifest.git" .repoURL }}'
        targetRevision: "master"
        path: '{{ default ( trimSuffix "/config.yaml" .values.app_path ) .srcPath }}'
        kustomize:
          buildOptions: "--enable-helm"
      syncPolicy:
        {{- if eq (index .path.segments 2) "mbs-discord-bot" }}
        {}
        {{- else }}
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        retry:
          limit: 30
          backoff:
            duration: 20s
            factor: 1
            maxDuration: 20s
        # syncOptions:
        # - CreateNamespace=true
        {{- end }}
  templatePatch: |
    metadata:
      labels:
        app.kubernetes.io/name: '{{ index .path.segments 2 }}'
        {{- range $key, $value := .labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      annotations:
        {{- range $key, $value := .annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
  syncPolicy: {}