# App Argo CD: playground-localstack
# Secret LOCALSTACK_AUTH_TOKEN: file trong repo private — metadata.namespace phải là localstack (không dùng datadog).
destNamespace: localstack
annotations:
  argocd.argoproj.io/sync-wave: "3"
