image:
  repository: localstack/localstack-pro
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

envFrom:
  - secretRef:
      name: localstack-secret

extraEnvVars:
  - name: LOCALSTACK_HOST
    value: "localstack.hoangvu75.space:443"
  # Cho phép Web App (https://app.localstack.cloud) gọi API cross-origin tới instance này
  - name: EXTRA_CORS_ALLOWED_ORIGINS
    value: "https://app.localstack.cloud"

service:
  type: ClusterIP

persistence:
  enabled: true

mountDind:
  enabled: true
  forceTLS: false
  image: public.ecr.aws/docker/library/docker:24-dind

lambda:
  executor: docker

resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    memory: 4Gi

tests:
  enabled: false
