image:
  repository: localstack/localstack-pro
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

envFrom:
  - secretRef:
      name: localstack-secret

service:
  type: ClusterIP

persistence:
  enabled: true

mountDind:
  enabled: true
  forceTLS: false
  image: public.ecr.aws/docker/library/docker:24-dind

lambda:
  executor: docker

resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    memory: 4Gi

tests:
  enabled: false
