# Ingress backend port = service.edgeService.targetPort (4566 in values.yaml).
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://app.localstack.cloud"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-MD5,Range,Authorization,X-Amz-Date,X-Amz-Security-Token,X-Amz-Content-Sha256,X-Amz-Target,X-Amz-User-Agent,X-Amz-Acl,X-Amz-Trailer,X-Amz-Decoded-Content-Length,X-Amz-Sdk-Checksum-Algorithm,X-Amz-Checksum-Algorithm,X-Amz-Checksum-Crc32,X-Amz-Checksum-Crc32c,X-Amz-Checksum-Sha1,X-Amz-Checksum-Sha256,X-Localstack-Target,amz-sdk-invocation-id,amz-sdk-request"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-expose-headers: "ETag,x-amz-request-id,x-amz-version-id,x-amz-id-2"
    nginx.ingress.kubernetes.io/cors-max-age: "86400"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/websocket-services: "localstack"
    nginx.ingress.kubernetes.io/server-alias: "localstack.localhost"
  hosts:
    - host: localstack.hoangvu75.space
      paths:
        - path: /
          pathType: Prefix
