image:
  repository: localstack/localstack-pro
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

envFrom:
  - secretRef:
      name: localstack-secret

service:
  type: ClusterIP

persistence:
  enabled: true

mountDind:
  enabled: true
  forceTLS: false

lambda:
  executor: docker

resources:
  requests:
    cpu: 250m
    memory: 768Mi
  limits:
    memory: 2Gi

tests:
  enabled: false
