apiVersion: v1
kind: Namespace
metadata:
  name: test1
  labels:
    environment: development
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: test2
  labels:
    environment: staging
    managed-by: argocd

