
api:
  insecure: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true
  kubernetesGateway: {}

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  tcp:
    address: ":9000"
  udp:
    address: ":9001/udp"
  metrics:
    address: ":9082"

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true

accessLog:
  format: json
  filters:
    statusCodes: ["200-499"]
  fields:
    defaultMode: keep

tracing:
  otlp:
    http:
      endpoint: http://datadog.datadog:4318/v1/traces

log:
  level: INFO
