hostname: rancher.hoangvu75.space

bootstrapPassword: "admin"

replicas: 1

ingress:
  tls:
    source: secret

httpRoute:
  enabled: true
  parentRefs:
    - name: shared-gateway
      namespace: gateway-api
  hostnames:
    - "rancher.hoangvu75.space"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: rancher
          port: 80
