apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.basicAuth.enabled }}
  basicAuthPassword: {{ .Values.config.basicAuth.password | quote }}
  {{- end }}
  encryptionKey: {{ .Values.config.encryptionKey | quote }}
