controller:
  service:
    type: NodePort
  extraArgs:
    enable-ssl-passthrough: ""
  config:
    use-forwarded-headers: "true"
    use-gzip: "true"
    gzip-level: "5"
    gzip-min-length: "256"
    proxy-buffering: "on"
    proxy-buffer-size: "8k"
    proxy-buffers-number: "8"
    proxy-busy-buffers-size: "16k"
    upstream-keepalive-connections: "320"
    upstream-keepalive-time: "1h"
    upstream-keepalive-requests: "10000"
    keep-alive: "75"
    keep-alive-requests: "10000"
  metrics:
    enabled: true
