apiVersion: v2
name: ingress-nginx
description: Nginx Ingress Controller Wrapper
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: ingress-nginx
    version: 4.9.0
    repository: https://kubernetes.github.io/ingress-nginx
