apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: application
  repo: oci://ghcr.io/hoangvu75/helm_application
  releaseName: hello-api
  namespace: hello-api
  version: 6.16.1
  valuesFile: values.yaml
  additionalValuesFiles:
    - values-service.yaml
