httpRoute:
  enabled: true
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  parentRefs:
    - name: shared-gateway
      namespace: gateway-api
  hostnames:
    - api.hoangvu75.space
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /helloworld
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Port
                value: "443"
      backendRefs:
        - name: hello-api
          port: 5678
