apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gateway-api
    repo: https://kubernetes-sigs.github.io/gateway-api
    version: "1.2.0"
    releaseName: gateway-api-crds
    namespace: gateway-api
    includeCRDs: true
    
  - name: nginx-gateway-fabric
    repo: https://nginxinc.github.io/nginx-gateway-fabric-helm-charts
    version: "0.8.0"
    releaseName: nginx-gateway-fabric
    namespace: gateway-api
    valuesFile: values.yaml
