apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
type: Opaque
stringData:
  jenkins-admin-password: {{ .Values.config.adminPassword | quote }}
