apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    environment: development
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-tools
  labels:
    environment: infrastructure
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  labels:
    environment: infrastructure
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    environment: infrastructure
    managed-by: argocd
