apiVersion: v1
kind: Namespace
metadata:
  name: test-1
  labels:
    environment: development
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-tools
  labels:
    environment: infrastructure
    managed-by: argocd

