apiVersion: management.cattle.io/v3
kind: Project
metadata:
  name: p-development
  namespace: local  # Cluster ID (thường là 'local' cho local cluster)
  labels:
    cattle.io/creator: admin
  annotations:
    # ArgoCD sync wave: tạo projects trước (wave -1)
    argocd.argoproj.io/sync-wave: "-1"
spec:
  displayName: Development
  description: Development environment for testing applications
  clusterName: local
---
apiVersion: management.cattle.io/v3
kind: Project
metadata:
  name: p-staging
  namespace: local
  labels:
    cattle.io/creator: admin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  displayName: Staging
  description: Staging environment for pre-production testing
  clusterName: local
---
apiVersion: management.cattle.io/v3
kind: Project
metadata:
  name: p-devops
  namespace: local
  labels:
    cattle.io/creator: admin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  displayName: DevOps Tools
  description: DevOps tools like Helm, ArgoCD, Jenkins, etc.
  clusterName: local

