apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: oauth2-client
  annotations:
    kubernetes.io/ingress.class: kong
    argocd.argoproj.io/sync-wave: "3"
username: oauth2-client
credentials:
  - oauth2-client-credential
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-client-credential
  labels:
    konghq.com/credential: oauth2
  annotations:
    kubernetes.io/ingress.class: kong
    argocd.argoproj.io/sync-wave: "3"
stringData:
  client_id: kong-oauth2-client
  client_secret: changeme-oauth2-secret
  name: OAuth2 Client App
  redirect_uris: "[]"
type: Opaque
