applicationName: cloudflared

deployment:
  enabled: true
  replicas: 2
  image:
    repository: cloudflare/cloudflared
    tag: "2026.3.0"
    pullPolicy: IfNotPresent
  ports: []
  args:
    - tunnel
    - --no-autoupdate
    - --protocol
    - http2
    - run
    - --token
    - $(TUNNEL_TOKEN)
  envFrom:
    - type: secret
      name: cloudflared-credentials
  
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  containerSecurityContext:
    runAsNonRoot: false
    readOnlyRootFilesystem: false

service:
  enabled: false
