# cluster-resources/<cluster>/namespace.yaml — quy hoạch tạo namespace (giống công ty). Sync-wave -1 để tạo trước app.
# Project: Playground
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-api
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    routing.hoangvu75.space/expose: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    routing.hoangvu75.space/expose: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: datadog
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld-api
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    routing.hoangvu75.space/expose: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tcp-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    routing.hoangvu75.space/expose: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: udp-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    routing.hoangvu75.space/expose: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-check
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kong-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    routing.hoangvu75.space/expose: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    routing.hoangvu75.space/expose: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
