---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: maintenance
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJhMkZtYVdodllXNW5kblU2WjJod1h6aHFiMlpKWkZSWGRUWTRRVTVUUlV0TU5HUkdXblZXYmpOTWRUaHFiREpqYjB0TGNBPT0ifX19
