apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kong
  repo: https://charts.konghq.com
  releaseName: kong
  namespace: kong
  version: "2.45.0"
  valuesFile: values.yaml

resources:
  - httproute-kong.yaml
  - externalname-hello-api.yaml
  - kong-plugin-key-auth.yaml
  - kong-consumer.yaml
  - hello-api-ingress.yaml
