---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-api
  namespace: kong-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: ExternalName
  externalName: helloworld-api.helloworld-api.svc.cluster.local
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: helloworld-api-mtls
  namespace: kong-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  host: helloworld-api.kong-gateway.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
