apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-token
  annotations:
    konghq.com/plugins: oauth2
    konghq.com/strip-path: "false"
    argocd.argoproj.io/sync-wave: "3"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: helloworld-api
                port:
                  number: 5678
