apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: default-user
  annotations:
    kubernetes.io/ingress.class: kong
    argocd.argoproj.io/sync-wave: "3"
username: default-user
credentials:
  - default-user-key-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: default-user-key-auth
  labels:
    konghq.com/credential: key-auth
  annotations:
    kubernetes.io/ingress.class: kong
    argocd.argoproj.io/sync-wave: "3"
stringData:
  key: dev-api-key-123
type: Opaque
