app:
  name: ingress-nginx
  namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    chart: ingress-nginx
  values: |
    controller:
      service:
        type: LoadBalancer
      config:
        use-forwarded-headers: "true"
      metrics:
        enabled: true
